"""
Agent 3: FinOps Optimizer
Trigger: Daily 6 AM IST (EventBridge schedule)
Action:  Analyse 7-day cost trends -> Bedrock recommendations -> GitHub issue
"""
import json, boto3, os, logging, urllib.request
from datetime import datetime, timezone, timedelta
from common.bedrock_client import invoke_claude
from common.notifications import publish_alert, log_event

logger = logging.getLogger(); logger.setLevel(logging.INFO)
ce  = boto3.client("ce",  region_name="us-east-1")
ssm = boto3.client("ssm", region_name="ap-south-1")
GITHUB_REPO = os.environ.get("GITHUB_REPO", "nimmalabalagit/compose-portal-application")

def get_cost_by_service(days=7):
    end   = datetime.now(timezone.utc).date()
    start = end - timedelta(days=days)
    resp  = ce.get_cost_and_usage(TimePeriod={"Start":str(start),"End":str(end)}, Granularity="DAILY",
        Metrics=["UnblendedCost"], GroupBy=[{"Type":"DIMENSION","Key":"SERVICE"}])
    totals = {}
    for result in resp.get("ResultsByTime",[]):
        for g in result.get("Groups",[]):
            svc = g["Keys"][0]; cost = float(g["Metrics"]["UnblendedCost"]["Amount"])
            totals[svc] = totals.get(svc, 0) + cost
    return sorted(totals.items(), key=lambda x: -x[1])

def get_github_token():
    return ssm.get_parameter(Name="/compose-portal/agents/github-token", WithDecryption=True)["Parameter"]["Value"]

def create_github_issue(token, title, body):
    payload = json.dumps({"title": title, "body": body, "labels": ["finops","automated"]}).encode()
    req = urllib.request.Request(f"https://api.github.com/repos/{GITHUB_REPO}/issues", data=payload,
        headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github.v3+json", "Content-Type": "application/json"}, method="POST")
    with urllib.request.urlopen(req, timeout=10) as r: return json.loads(r.read()).get("html_url","")

def lambda_handler(event, context):
    log_event("finops-optimizer", "triggered", {"schedule": "daily-6am-IST"})
    costs    = get_cost_by_service(days=7)
    total_7d = sum(c for _,c in costs)
    cost_summary = "\n".join([f"  {svc}: ${cost:.4f}" for svc,cost in costs[:10]])

    prompt = f"""You are the FinOps engineer for EstateFlow AI (personal EKS lab, ap-south-1).
7-DAY COSTS (total: ${total_7d:.4f}):\n{cost_summary}
Platform: EKS Karpenter Spot, Aurora db.t3.medium, Redis cache.t3.micro, 3 NAT Gateways.
Personal lab — cost minimisation is highest priority. Destroyed when not in use.
Provide: 1) COST SUMMARY 2) TOP 3 OPTIMISATIONS with estimated savings 3) IDLE RESOURCE AUDIT 4) WEEKLY TREND
Format as markdown for a GitHub issue."""

    analysis  = invoke_claude(prompt=prompt, system="You are a FinOps specialist. Focus on actionable cost savings.", model="anthropic.claude-3-haiku-20240307-v1:0", max_tokens=1024)
    try:
        token     = get_github_token()
        issue_url = create_github_issue(token,
            f"[FinOps] Weekly Cost Report — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
            f"## Weekly FinOps Report\n\n**7-day total: ${total_7d:.4f}**\n\n{analysis}\n\n*Generated by EstateFlow AI FinOps Optimizer Agent*")
    except Exception as e:
        issue_url = f"GitHub issue failed: {e}"

    result = {"period_days": 7, "total_cost_usd": round(total_7d,4), "top_services": costs[:5], "github_issue": issue_url}
    publish_alert(subject=f"[FinOps] Weekly report — ${total_7d:.4f}", message=result, severity="INFO")
    return {"statusCode": 200, "body": json.dumps(result, default=str)}
