apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Images updated by GitHub Actions deploy.yml:
# kustomize edit set image gateway-service=...ecr.../${GITHUB_SHA}
images:
  - name: gateway-service
    newName: 371056712467.dkr.ecr.ap-south-1.amazonaws.com/gateway-service
    newTag: REPLACE_WITH_SHA    # GitHub Actions replaces this
  - name: user-service
    newName: 371056712467.dkr.ecr.ap-south-1.amazonaws.com/user-service
    newTag: REPLACE_WITH_SHA
  - name: product-service
    newName: 371056712467.dkr.ecr.ap-south-1.amazonaws.com/product-service
    newTag: REPLACE_WITH_SHA
  - name: order-service
    newName: 371056712467.dkr.ecr.ap-south-1.amazonaws.com/order-service
    newTag: REPLACE_WITH_SHA