apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: compose-portal-mtls
  namespace: compose-portal
spec:
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: user-service-authz
  namespace: compose-portal
spec:
  selector:
    matchLabels:
      app: user-service
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/compose-portal/sa/gateway-service-sa"]
