"""
Agent 5: PR Reviewer
Trigger: GitHub PR opened/updated -> webhook -> API GW -> Lambda
Action:  Review Terraform/K8s/Dockerfile diffs -> security analysis -> PR comment
"""
import json, boto3, os, logging, urllib.request
from common.bedrock_client import invoke_claude
from common.notifications import log_event

logger = logging.getLogger(); logger.setLevel(logging.INFO)
ssm = boto3.client("ssm", region_name="ap-south-1")
GITHUB_REPO = os.environ.get("GITHUB_REPO", "nimmalabalagit/compose-portal-application")

def get_github_token():
    return ssm.get_parameter(Name="/compose-portal/agents/github-token", WithDecryption=True)["Parameter"]["Value"]

def github_api(token, path, method="GET", data=None):
    url     = f"https://api.github.com/repos/{GITHUB_REPO}/{path}"
    payload = json.dumps(data).encode() if data else None
    req     = urllib.request.Request(url, data=payload, method=method,
        headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github.v3+json", "Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=15) as r: return json.loads(r.read())

def get_pr_diff(token, pr_number):
    files = github_api(token, f"pulls/{pr_number}/files")
    parts = []
    for f in files[:20]:
        parts.append(f"FILE ({f.get('status','')}): {f.get('filename','')}\n{f.get('patch','')[:2000]}")
    return "\n\n---\n\n".join(parts)

def lambda_handler(event, context):
    log_event("pr-reviewer", "triggered", {})
    body      = event.get("body","{}"); body = json.loads(body) if isinstance(body, str) else body
    action    = body.get("action","")
    if action not in ("opened","synchronize","reopened"): return {"statusCode":200,"body":"Skipping"}
    pr        = body.get("pull_request",{})
    pr_number = pr.get("number",0)
    pr_title  = pr.get("title","")
    pr_author = pr.get("user",{}).get("login","")
    token     = get_github_token()
    pr_diff   = get_pr_diff(token, pr_number)

    prompt = f"""Review this pull request for EstateFlow AI (production EKS platform).
PR #{pr_number}: {pr_title} by {pr_author}
CHANGED FILES:\n{pr_diff}
Check for: hardcoded secrets, IAM wildcards, missing resource limits/probes, missing PDB,
missing securityContext, Terraform missing tags, hardcoded region/account, blast radius.
Use checkmarks: ✅ good, ⚠️ warning, ❌ blocking issue.
End with APPROVE / REQUEST CHANGES / COMMENT ONLY recommendation."""

    review = invoke_claude(prompt=prompt, system="You are a senior DevSecOps engineer. Be specific about file references.", model="anthropic.claude-3-5-sonnet-20241022-v2:0")
    try:
        github_api(token, f"issues/{pr_number}/comments", method="POST",
            data={"body": f"## AI PR Review — EstateFlow AI\n\n{review}\n\n*Generated by EstateFlow AI PR Reviewer Agent*"})
        log_event("pr-reviewer", "review_posted", {"pr": pr_number})
    except Exception as e:
        logger.error(f"Could not post review: {e}")

    return {"statusCode": 200, "body": json.dumps({"pr": pr_number, "preview": review[:300]}, default=str)}
