"""
Agent 4: Pipeline Doctor
Trigger: GitHub Actions workflow failure -> webhook -> API GW -> Lambda
Action:  Analyse failure -> Bedrock diagnosis -> comment on GitHub commit
"""
import json, boto3, os, logging, urllib.request
from common.bedrock_client import invoke_claude
from common.notifications import publish_alert, log_event

logger = logging.getLogger(); logger.setLevel(logging.INFO)
ssm = boto3.client("ssm", region_name="ap-south-1")
GITHUB_REPO = os.environ.get("GITHUB_REPO", "nimmalabalagit/compose-portal-application")

def get_github_token():
    return ssm.get_parameter(Name="/compose-portal/agents/github-token", WithDecryption=True)["Parameter"]["Value"]

def github_api(token, path, method="GET", data=None):
    url     = f"https://api.github.com/repos/{GITHUB_REPO}/{path}"
    payload = json.dumps(data).encode() if data else None
    req     = urllib.request.Request(url, data=payload, method=method,
        headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github.v3+json", "Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=15) as r: return json.loads(r.read())

def get_workflow_logs(token, run_id):
    try:
        jobs      = github_api(token, f"actions/runs/{run_id}/jobs").get("jobs",[])
        log_lines = []
        for job in jobs:
            if job.get("conclusion") == "failure":
                log_lines.append(f"FAILED JOB: {job['name']}")
                for step in job.get("steps",[]):
                    log_lines.append(f"  step [{step.get('conclusion','')}]: {step['name']}")
        return "\n".join(log_lines) or "No failed steps found"
    except Exception as e:
        return f"Could not fetch logs: {e}"

def lambda_handler(event, context):
    log_event("pipeline-doctor", "triggered", {})
    body       = event.get("body","{}"); body = json.loads(body) if isinstance(body, str) else body
    workflow   = body.get("workflow_run", body.get("workflow_job",{}))
    conclusion = workflow.get("conclusion","")
    if conclusion != "failure": return {"statusCode":200,"body":"Not a failure — skipping"}
    run_id     = str(workflow.get("id",""))
    run_name   = workflow.get("name","unknown")
    branch     = workflow.get("head_branch","main")
    commit_sha = workflow.get("head_sha","")
    token      = get_github_token()
    job_logs   = get_workflow_logs(token, run_id)

    prompt = f"""Diagnose this GitHub Actions failure for EstateFlow AI.
WORKFLOW: {run_name} | BRANCH: {branch} | COMMIT: {commit_sha[:8]}
FAILED STEPS:\n{job_logs}
Known issues: ECR immutable tag (delete digest first), --provenance=false for Docker buildx,
Maven must run from repo root with -pl services/SERVICE -am, OIDC token expiry, Trivy CRITICAL block.
Provide: 1) ROOT CAUSE 2) EXACT FIX (command) 3) HOW TO VERIFY 4) PREVENTION"""

    diagnosis = invoke_claude(prompt=prompt, system="You are a CI/CD expert. Give exact fix commands. Be concise.", model="anthropic.claude-3-5-sonnet-20241022-v2:0")
    try:
        github_api(token, f"commits/{commit_sha}/comments", method="POST",
            data={"body": f"## Pipeline Doctor Analysis\n\n**Failed:** {run_name}\n\n{diagnosis}\n\n*Generated by EstateFlow AI Pipeline Doctor Agent*"})
    except Exception as e:
        logger.warning(f"Could not post comment: {e}")

    result = {"workflow": run_name, "branch": branch, "diagnosis_preview": diagnosis[:300]}
    publish_alert(subject=f"[Pipeline] Failed: {run_name} on {branch}", message=result, severity="HIGH")
    return {"statusCode": 200, "body": json.dumps(result, default=str)}
