apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: compose-portal-services
  namespace: observability
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - compose-portal
  selector:
    matchLabels:
      monitored: "true"
  endpoints:
    - path: /actuator/prometheus
      port: http
      interval: 15s
