"""
Agent 7: Capacity Planner
Trigger: Weekly Monday 9 AM IST (EventBridge schedule)
Action:  Analyse HPA + node metrics -> Bedrock capacity forecast -> GitHub issue
"""
import json, boto3, os, logging, urllib.request
from datetime import datetime, timezone, timedelta
from common.bedrock_client import invoke_claude
from common.notifications import log_event

logger = logging.getLogger(); logger.setLevel(logging.INFO)
cw  = boto3.client("cloudwatch", region_name="ap-south-1")
ssm = boto3.client("ssm",        region_name="ap-south-1")
GITHUB_REPO  = os.environ.get("GITHUB_REPO",  "nimmalabalagit/compose-portal-application")
CLUSTER_NAME = os.environ.get("CLUSTER_NAME", "compose-portal-dev-eks")

def get_metric_avg(namespace, metric, dimensions, days=7):
    end   = datetime.now(timezone.utc); start = end - timedelta(days=days)
    resp  = cw.get_metric_statistics(Namespace=namespace, MetricName=metric, Dimensions=dimensions,
        StartTime=start, EndTime=end, Period=3600, Statistics=["Average"])
    pts = resp.get("Datapoints",[])
    return sum(p["Average"] for p in pts)/len(pts) if pts else 0.0

def get_github_token():
    return ssm.get_parameter(Name="/compose-portal/agents/github-token", WithDecryption=True)["Parameter"]["Value"]

def lambda_handler(event, context):
    log_event("capacity-planner", "triggered", {"schedule": "weekly-monday"})
    node_cpu    = get_metric_avg("ContainerInsights","node_cpu_utilization",    [{"Name":"ClusterName","Value":CLUSTER_NAME}])
    node_memory = get_metric_avg("ContainerInsights","node_memory_utilization", [{"Name":"ClusterName","Value":CLUSTER_NAME}])

    prompt = f"""You are the capacity planner for EstateFlow AI (personal EKS lab, ap-south-1).
7-DAY AVERAGES: Node CPU: {node_cpu:.1f}% | Node Memory: {node_memory:.1f}%
CONFIG: Karpenter NodePool t3.medium/t3a.medium/m5.large Spot. HPA min=1 max=3 CPU target=70%.
System node: t3.medium x1 On-Demand. Personal lab — scale to zero when not in use is priority.
Provide: 1) UTILISATION SUMMARY 2) RECOMMENDATIONS (adjust HPA/Karpenter) 3) COST OPTIMISATION
Format as markdown for a GitHub issue."""

    report = invoke_claude(prompt=prompt, system="You are a Kubernetes capacity planner. Give specific HPA/Karpenter config changes.", model="anthropic.claude-3-haiku-20240307-v1:0", max_tokens=1024)
    try:
        token   = get_github_token()
        payload = json.dumps({"title": f"[Capacity] Weekly Report — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
            "body": f"## Weekly Capacity Report\n\n{report}\n\n*Generated by EstateFlow AI Capacity Planner Agent*", "labels": ["capacity","automated"]}).encode()
        req = urllib.request.Request(f"https://api.github.com/repos/{GITHUB_REPO}/issues", data=payload,
            headers={"Authorization": f"Bearer {get_github_token()}", "Accept": "application/vnd.github.v3+json", "Content-Type": "application/json"}, method="POST")
        with urllib.request.urlopen(req, timeout=10) as r: issue_url = json.loads(r.read()).get("html_url","")
    except Exception as e:
        issue_url = f"GitHub issue failed: {e}"

    return {"statusCode": 200, "body": json.dumps({"report_preview": report[:300], "github_issue": issue_url}, default=str)}
