apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
  - target:
      kind: HorizontalPodAutoscaler
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
  - target:
      kind: ExternalSecret
    patch: |
      - op: replace
        path: /spec/refreshInterval
        value: "5m"
images:
  - name: 371056712467.dkr.ecr.ap-south-1.amazonaws.com/gateway-service
    newTag: sha-7468b569f306f9ce42aeecc6e886fb1021114c7e
  - name: 371056712467.dkr.ecr.ap-south-1.amazonaws.com/user-service
    newTag: sha-817430ed15ea2434e907d4dd824383f19ca4dd90
  - name: 371056712467.dkr.ecr.ap-south-1.amazonaws.com/product-service
    newTag: sha-817430ed15ea2434e907d4dd824383f19ca4dd90
  - name: 371056712467.dkr.ecr.ap-south-1.amazonaws.com/order-service
    newTag: sha-817430ed15ea2434e907d4dd824383f19ca4dd90
