"""
Agent 2: Security Remediator
Trigger: Security Hub finding -> EventBridge -> Lambda
Action:  Analyse finding -> Bedrock remediation -> GitHub issue
"""
import json, boto3, os, logging, urllib.request
from datetime import datetime, timezone
from common.bedrock_client import invoke_claude
from common.notifications import publish_alert, log_event

logger = logging.getLogger(); logger.setLevel(logging.INFO)
ssm = boto3.client("ssm", region_name="ap-south-1")
GITHUB_REPO = os.environ.get("GITHUB_REPO", "nimmalabalagit/compose-portal-application")

def get_github_token():
    return ssm.get_parameter(Name="/compose-portal/agents/github-token", WithDecryption=True)["Parameter"]["Value"]

def create_github_issue(token, title, body):
    payload = json.dumps({"title": title, "body": body, "labels": ["security","automated"]}).encode()
    req = urllib.request.Request(f"https://api.github.com/repos/{GITHUB_REPO}/issues", data=payload,
        headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github.v3+json", "Content-Type": "application/json"}, method="POST")
    with urllib.request.urlopen(req, timeout=10) as r: return json.loads(r.read()).get("html_url","")

def lambda_handler(event, context):
    log_event("security-remediator", "triggered", {})
    detail    = event.get("detail", {})
    findings  = detail.get("findings", [detail])
    finding   = findings[0] if findings else {}
    title     = finding.get("Title", "Unknown Security Finding")
    severity  = finding.get("Severity", {}).get("Label", "MEDIUM")
    desc      = finding.get("Description", "No description")
    resource  = finding.get("Resources", [{}])[0]
    res_id    = resource.get("Id", "unknown")
    res_type  = resource.get("Type", "unknown")

    prompt = f"""You are remediating an AWS Security Hub finding for EstateFlow AI.
FINDING: {title} | SEVERITY: {severity}
DESCRIPTION: {desc}
RESOURCE TYPE: {res_type} | RESOURCE ID: {res_id}
Platform: EKS compose-portal-dev-eks, all infra in infrastructure/terraform/
Provide: 1) SEVERITY ASSESSMENT 2) REMEDIATION (exact Terraform or AWS CLI) 3) DETECTION 4) COMPLIANCE IMPACT 5) FILE TO MODIFY
Format as GitHub issue markdown."""

    remediation = invoke_claude(prompt=prompt, system="You are an AWS security specialist. Give exact Terraform and CLI remediation.", model="anthropic.claude-3-5-sonnet-20241022-v2:0")
    try:
        token     = get_github_token()
        issue_url = create_github_issue(token, f"[Security] [{severity}] {title}",
            f"## Security Hub Finding\n**Severity:** {severity}\n**Resource:** `{res_id}`\n\n{remediation}\n\n*Generated by EstateFlow AI Security Remediator*\n*Human approval required before applying CRITICAL fixes.*")
    except Exception as e:
        issue_url = f"GitHub issue failed: {e}"

    result = {"finding": title, "severity": severity, "github_issue": issue_url, "human_required": severity in ("CRITICAL","HIGH")}
    publish_alert(subject=f"[Security] [{severity}] {title}", message=result, severity=severity)
    return {"statusCode": 200, "body": json.dumps(result, default=str)}
